### ISSUE TITLE
사용자와 평점에 대한 저장소를 결정하고 스키마를 작성한다.

### ISSUE THREAD

**Issue by rayfault** [surplusteam/daily-star#10]
사용할 데이터베이스와 테이블 스키마를 작성한다.
데이터베이스, 테이블 작성한 대한 쿼리를 프로젝트 파일에 첨부한다.

**Comment by ronnie-o** [comment]
## database
H2

## ddl
```sql
CREATE TABLE stars
(
id INT NOT NULL PRIMARY KEY,
start_point INT NOT NULL,
comment  VARCHAR(200),
created_at DATE NOT NULL,
modified_at DATE
);
```

http://stackoverflow.com/questions/24655684/spring-boot-default-h2-jdbc-connection-and-h2-console

**Comment by rayfault** [comment]
#11 에 있는 댓글로 대체합니다.
comment, 와 사용자의 pk 에 대한 데이터가 필요할 것 같습니다.
